services:
  voby-db:
    image: mysql
    restart: always
    container_name: voby-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d
    networks:
      - voby

  voby-adminer:
    image: adminer
    container_name: voby-adminer
    restart: always
    ports:
      - 8082:8080
    environment:
      ADMINER_DEFAULT_SERVER: voby-db
    networks:
      - voby

networks:
  voby:
    name: "voby"