services:
  client:
    build: .
    container_name: voby
    volumes:
      - .:/voby
    ports:
      - "82:82"
    command: sh -c "npm install && /voby/node_modules/@angular/cli/bin/ng.js serve --live-reload --host 0.0.0.0 --port 82"
    networks:
      voby:
        aliases:
          - 'client.voby.local'

networks:
  voby:
    name: voby
    external: true