# Generated by Django 4.0.4 on 2023-03-25 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voby', '0004_alter_example_user_alter_set_user_alter_word_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='word',
            field=models.ManyToManyField(related_name='examples', to='voby.word'),
        ),
        migrations.AlterField(
            model_name='set',
            name='vclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sets', to='voby.vclass'),
        ),
        migrations.AlterField(
            model_name='word',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='voby.set'),
        ),
    ]
