# Generated by Django 4.0.4 on 2023-03-26 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voby', '0005_alter_example_word_alter_set_vclass_alter_word_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='vclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='voby.vclass'),
        ),
    ]
