# Generated by Django 4.0.4 on 2023-04-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voby', '0006_alter_set_vclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
