# Generated by Django 4.0.4 on 2023-04-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voby', '0007_word_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vclass',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
