# Generated by Django 4.0.4 on 2023-04-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voby', '0008_word_created_alter_set_name_alter_vclass_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
