# Generated by Django 4.0.4 on 2023-04-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voby', '0009_alter_word_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
