# Generated by Django 4.0.4 on 2023-04-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voby', '0010_alter_word_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='plural',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
