# Generated by Django 4.0.4 on 2023-04-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voby', '0011_word_plural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vclass',
            name='source_language',
            field=models.CharField(choices=[('English', '🇬🇧'), ('French', '🇫🇷'), ('Spanish', '🇪🇸'), ('German', '🇩🇪'), ('Italian', '🇮🇹'), ('Japanese', '🇯🇵'), ('Korean', '🇰🇷'), ('Mandarin Chinese', '🇨🇳'), ('Russian', '🇷🇺'), ('Hindi', '🇮🇳'), ('Portuguese', '🇧🇷'), ('Arabic', '🇸🇦'), ('Dutch', '🇳🇱'), ('Swedish', '🇸🇪'), ('Norwegian', '🇳🇴'), ('Danish', '🇩🇰'), ('Finnish', '🇫🇮'), ('Turkish', '🇹🇷'), ('Polish', '🇵🇱'), ('Czech', '🇨🇿'), ('Greek', '🇬🇷'), ('Hungarian', '🇭🇺'), ('Romanian', '🇷🇴'), ('Bulgarian', '🇧🇬'), ('Croatian', '🇭🇷'), ('Serbian', '🇷🇸'), ('Slovak', '🇸🇰'), ('Slovenian', '🇸🇮'), ('Estonian', '🇪🇪'), ('Latvian', '🇱🇻'), ('Lithuanian', '🇱🇹'), ('Ukrainian', '🇺🇦'), ('Hebrew', '🇮🇱'), ('Thai', '🇹🇭'), ('Vietnamese', '🇻🇳'), ('Indonesian', '🇮🇩'), ('Malay', '🇲🇾'), ('Tagalog', '🇵🇭'), ('Bengali', '🇧🇩'), ('Punjabi', '🇮🇳'), ('Tamil', '🇮🇳'), ('Telugu', '🇮🇳'), ('Marathi', '🇮🇳'), ('Gujarati', '🇮🇳'), ('Urdu', '🇵🇰'), ('Farsi', '🇮🇷'), ('Kurdish', '🇮🇶'), ('Swahili', '🇹🇿'), ('Zulu', '🇿🇦'), ('Afrikaans', '🇿🇦'), ('Xhosa', '🇿🇦'), ('Yoruba', '🇳🇬'), ('Igbo', '🇳🇬'), ('Hausa', '🇳🇬'), ('Amharic', '🇪🇹')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vclass',
            name='target_language',
            field=models.CharField(choices=[('English', '🇬🇧'), ('French', '🇫🇷'), ('Spanish', '🇪🇸'), ('German', '🇩🇪'), ('Italian', '🇮🇹'), ('Japanese', '🇯🇵'), ('Korean', '🇰🇷'), ('Mandarin Chinese', '🇨🇳'), ('Russian', '🇷🇺'), ('Hindi', '🇮🇳'), ('Portuguese', '🇧🇷'), ('Arabic', '🇸🇦'), ('Dutch', '🇳🇱'), ('Swedish', '🇸🇪'), ('Norwegian', '🇳🇴'), ('Danish', '🇩🇰'), ('Finnish', '🇫🇮'), ('Turkish', '🇹🇷'), ('Polish', '🇵🇱'), ('Czech', '🇨🇿'), ('Greek', '🇬🇷'), ('Hungarian', '🇭🇺'), ('Romanian', '🇷🇴'), ('Bulgarian', '🇧🇬'), ('Croatian', '🇭🇷'), ('Serbian', '🇷🇸'), ('Slovak', '🇸🇰'), ('Slovenian', '🇸🇮'), ('Estonian', '🇪🇪'), ('Latvian', '🇱🇻'), ('Lithuanian', '🇱🇹'), ('Ukrainian', '🇺🇦'), ('Hebrew', '🇮🇱'), ('Thai', '🇹🇭'), ('Vietnamese', '🇻🇳'), ('Indonesian', '🇮🇩'), ('Malay', '🇲🇾'), ('Tagalog', '🇵🇭'), ('Bengali', '🇧🇩'), ('Punjabi', '🇮🇳'), ('Tamil', '🇮🇳'), ('Telugu', '🇮🇳'), ('Marathi', '🇮🇳'), ('Gujarati', '🇮🇳'), ('Urdu', '🇵🇰'), ('Farsi', '🇮🇷'), ('Kurdish', '🇮🇶'), ('Swahili', '🇹🇿'), ('Zulu', '🇿🇦'), ('Afrikaans', '🇿🇦'), ('Xhosa', '🇿🇦'), ('Yoruba', '🇳🇬'), ('Igbo', '🇳🇬'), ('Hausa', '🇳🇬'), ('Amharic', '🇪🇹')], max_length=20),
        ),
    ]
