# Generated by Django 4.0.4 on 2023-04-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voby', '0012_alter_vclass_source_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='related_words',
            field=models.ManyToManyField(null=True, related_name='rel_words', to='voby.word'),
        ),
    ]
