# Generated by Django 4.0.4 on 2023-04-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voby', '0015_alter_word_related_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
