# Generated by Django 4.0.4 on 2023-05-07 09:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voby', '0017_testanswer_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestAnswer',
            new_name='QuizAnswer',
        ),
    ]
