# Generated by Django 4.0.4 on 2023-10-22 09:28

from django.db import migrations, models
import django.db.models.deletion
from ..models import Word


class Migration(migrations.Migration):


    def populateTranslations(apps, schema_editor):
        Words = apps.get_model('voby', 'Word')
        Translation = apps.get_model('voby', 'Translation')

        all_words = Words.objects.all()
        word: Word
        for word in all_words:
            prev_translations = [t.strip() for t in word.translation.split('/')]
            for translation in prev_translations:
                Translation(word=word, value=translation).save()


    dependencies = [
        ('voby', '0020_usershortcuts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=120)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='voby.word')),
            ],
        ),
        migrations.RunPython(populateTranslations, migrations.RunPython.noop)
    ]
