# Generated by Django 4.0.4 on 2023-11-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voby', '0023_option'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='unique-key-user'),
        ),
    ]
