# Generated by Django 4.2 on 2025-01-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voby', '0024_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='set',
        ),
        migrations.AddField(
            model_name='word',
            name='set',
            field=models.ManyToManyField(related_name='words', to='voby.set'),
        ),
    ]
