# Generated by Django 4.2 on 2025-08-17 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voby', '0025_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='vclass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='voby.vclass'),
            preserve_default=False,
        ),
    ]
