# Generated by Django 4.2 on 2025-03-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voby', '0025_remove_word_set_word_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='set',
            new_name='sets',
        ),
    ]
