# Generated by Django 4.2 on 2025-09-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voby', '0026_tag_vclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='learned_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vclass',
            name='source_language',
            field=models.CharField(choices=[('English', 'English 🇬🇧'), ('French', 'French 🇫🇷'), ('Spanish', 'Spanish 🇪🇸'), ('German', 'German 🇩🇪'), ('Italian', 'Italian 🇮🇹'), ('Japanese', 'Japanese 🇯🇵'), ('Korean', 'Korean 🇰🇷'), ('Mandarin Chinese', 'Mandarin Chinese 🇨🇳'), ('Russian', 'Russian 🇷🇺'), ('Hindi', 'Hindi 🇮🇳'), ('Portuguese', 'Portuguese 🇧🇷'), ('Arabic', 'Arabic 🇸🇦'), ('Dutch', 'Dutch 🇳🇱'), ('Swedish', 'Swedish 🇸🇪'), ('Norwegian', 'Norwegian 🇳🇴'), ('Danish', 'Danish 🇩🇰'), ('Finnish', 'Finnish 🇫🇮'), ('Turkish', 'Turkish 🇹🇷'), ('Polish', 'Polish 🇵🇱'), ('Czech', 'Czech 🇨🇿'), ('Greek', 'Greek 🇬🇷'), ('Hungarian', 'Hungarian 🇭🇺'), ('Romanian', 'Romanian 🇷🇴'), ('Bulgarian', 'Bulgarian 🇧🇬'), ('Croatian', 'Croatian 🇭🇷'), ('Serbian', 'Serbian 🇷🇸'), ('Slovak', 'Slovak 🇸🇰'), ('Slovenian', 'Slovenian 🇸🇮'), ('Estonian', 'Estonian 🇪🇪'), ('Latvian', 'Latvian 🇱🇻'), ('Lithuanian', 'Lithuanian 🇱🇹'), ('Ukrainian', 'Ukrainian 🇺🇦'), ('Hebrew', 'Hebrew 🇮🇱'), ('Thai', 'Thai 🇹🇭'), ('Vietnamese', 'Vietnamese 🇻🇳'), ('Indonesian', 'Indonesian 🇮🇩'), ('Malay', 'Malay 🇲🇾'), ('Tagalog', 'Tagalog 🇵🇭'), ('Bengali', 'Bengali 🇧🇩'), ('Punjabi', 'Punjabi 🇮🇳'), ('Tamil', 'Tamil 🇮🇳'), ('Telugu', 'Telugu 🇮🇳'), ('Marathi', 'Marathi 🇮🇳'), ('Gujarati', 'Gujarati 🇮🇳'), ('Urdu', 'Urdu 🇵🇰'), ('Farsi', 'Farsi 🇮🇷'), ('Kurdish', 'Kurdish 🇮🇶'), ('Swahili', 'Swahili 🇹🇿'), ('Zulu', 'Zulu 🇿🇦'), ('Afrikaans', 'Afrikaans 🇿🇦'), ('Xhosa', 'Xhosa 🇿🇦'), ('Yoruba', 'Yoruba 🇳🇬'), ('Igbo', 'Igbo 🇳🇬'), ('Hausa', 'Hausa 🇳🇬'), ('Amharic', 'Amharic 🇪🇹')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vclass',
            name='target_language',
            field=models.CharField(choices=[('English', 'English 🇬🇧'), ('French', 'French 🇫🇷'), ('Spanish', 'Spanish 🇪🇸'), ('German', 'German 🇩🇪'), ('Italian', 'Italian 🇮🇹'), ('Japanese', 'Japanese 🇯🇵'), ('Korean', 'Korean 🇰🇷'), ('Mandarin Chinese', 'Mandarin Chinese 🇨🇳'), ('Russian', 'Russian 🇷🇺'), ('Hindi', 'Hindi 🇮🇳'), ('Portuguese', 'Portuguese 🇧🇷'), ('Arabic', 'Arabic 🇸🇦'), ('Dutch', 'Dutch 🇳🇱'), ('Swedish', 'Swedish 🇸🇪'), ('Norwegian', 'Norwegian 🇳🇴'), ('Danish', 'Danish 🇩🇰'), ('Finnish', 'Finnish 🇫🇮'), ('Turkish', 'Turkish 🇹🇷'), ('Polish', 'Polish 🇵🇱'), ('Czech', 'Czech 🇨🇿'), ('Greek', 'Greek 🇬🇷'), ('Hungarian', 'Hungarian 🇭🇺'), ('Romanian', 'Romanian 🇷🇴'), ('Bulgarian', 'Bulgarian 🇧🇬'), ('Croatian', 'Croatian 🇭🇷'), ('Serbian', 'Serbian 🇷🇸'), ('Slovak', 'Slovak 🇸🇰'), ('Slovenian', 'Slovenian 🇸🇮'), ('Estonian', 'Estonian 🇪🇪'), ('Latvian', 'Latvian 🇱🇻'), ('Lithuanian', 'Lithuanian 🇱🇹'), ('Ukrainian', 'Ukrainian 🇺🇦'), ('Hebrew', 'Hebrew 🇮🇱'), ('Thai', 'Thai 🇹🇭'), ('Vietnamese', 'Vietnamese 🇻🇳'), ('Indonesian', 'Indonesian 🇮🇩'), ('Malay', 'Malay 🇲🇾'), ('Tagalog', 'Tagalog 🇵🇭'), ('Bengali', 'Bengali 🇧🇩'), ('Punjabi', 'Punjabi 🇮🇳'), ('Tamil', 'Tamil 🇮🇳'), ('Telugu', 'Telugu 🇮🇳'), ('Marathi', 'Marathi 🇮🇳'), ('Gujarati', 'Gujarati 🇮🇳'), ('Urdu', 'Urdu 🇵🇰'), ('Farsi', 'Farsi 🇮🇷'), ('Kurdish', 'Kurdish 🇮🇶'), ('Swahili', 'Swahili 🇹🇿'), ('Zulu', 'Zulu 🇿🇦'), ('Afrikaans', 'Afrikaans 🇿🇦'), ('Xhosa', 'Xhosa 🇿🇦'), ('Yoruba', 'Yoruba 🇳🇬'), ('Igbo', 'Igbo 🇳🇬'), ('Hausa', 'Hausa 🇳🇬'), ('Amharic', 'Amharic 🇪🇹')], max_length=20),
        ),
    ]
