# Generated by Django 4.2 on 2025-09-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voby', '0027_word_learned_rate_alter_vclass_source_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_streak_set',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='learned_rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
