services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - LT_LOAD_LANGUAGES=en,es,fr,de,it,pt,ru,zh,ar,hi
      - LT_NO_STATS=true

    networks:
      voby:
        aliases:
          - "translation-api.voby.local"

    # In prod, this service runs without extra networks
    profiles: ["prod"]

networks:
  voby:
    external: true
