services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: translation-api
    ports:
      - "5000:5000"
    networks:
      voby:
        aliases:
          - "translation-api.voby.local"
    environment:
      - LT_LOAD_ONLY=en,es,fr,de,it,ru
      - LT_NO_STATS=true
      - LT_DISABLE_WEB_UI=true

networks:
  voby:
    name: voby
    external: true
