LANGUAGE_CODES = {
    "english": "en",
    "french": "fr",
    "spanish": "es",
    "german": "de",
    "italian": "it",
    "japanese": "ja",
    "korean": "ko",
    "mandarin chinese": "zh",
    "russian": "ru",
    "hindi": "hi",
    "portuguese": "pt",
    "arabic": "ar",
    "dutch": "nl",
    "swedish": "sv",
    "norwegian": "no",
    "danish": "da",
    "finnish": "fi",
    "turkish": "tr",
    "polish": "pl",
    "czech": "cs",
    "greek": "el",
    "hungarian": "hu",
    "romanian": "ro",
}
